/*
 * This source file was generated by the Gradle 'init' task
 */

import java.net.InetAddress;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("Hello socket-2 world!");

        var localhost = InetAddress.getByName("localhost");
        System.out.println(localhost.getHostName() + " :: " + localhost.getHostAddress());
        var addr = InetAddress.getByName("8.8.8.8");
        System.out.println(addr.getHostName() + " :: " + addr.getHostAddress());

        HybridCarImpl hybridcar = new HybridCarImpl("carname");

        ICar car = (ICar) hybridcar;
        car.setSpeed(60);
        car.printCarName();

        IElectricCharge charger = (IElectricCharge) hybridcar;
        charger.chargeBattery(100);

        INavigation navigation = (INavigation) hybridcar;
        navigation.setDestination("北千住");
        navigation.printRoute();

        var clone = hybridcar.clone();
        clone.setSpeed(1000);
        clone.printCarName();
    }
}
