/*
 * This source file was generated by the Gradle 'init' task
 */


public class App {
    public static void main(String[] args) {
        System.out.println("Hello Network Programing and Cloud System Deveopment World.");
        Hello.main(args);
    }
}
