/*
 * This source file was generated by the Gradle 'init' task
 */


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertEquals(1 + 1, 2);
    }
}
